/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.ejemlos.s3;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author aleev
 */
public class Ejemplo13 extends javax.swing.JFrame {

    /**
     * Creates new form Ejemplo13
     */
    public Ejemplo13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenuColores = new javax.swing.JPopupMenu();
        mniRojo = new javax.swing.JMenuItem();
        mniVerde = new javax.swing.JMenuItem();
        mniAzul = new javax.swing.JMenuItem();

        mniRojo.setText("Rojo");
        mniRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniRojoActionPerformed(evt);
            }
        });
        pMenuColores.add(mniRojo);

        mniVerde.setText("Verde");
        mniVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVerdeActionPerformed(evt);
            }
        });
        pMenuColores.add(mniVerde);

        mniAzul.setText("Azul");
        mniAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAzulActionPerformed(evt);
            }
        });
        pMenuColores.add(mniAzul);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniRojoActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.red);
    }//GEN-LAST:event_mniRojoActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == 1)
            JOptionPane.showMessageDialog(null, "Clic izquierdo");
        if (evt.getButton() == 2)
            JOptionPane.showMessageDialog(null, "Clic centrral");
        if (evt.getButton() == 3) //Cuando clic derecho mostramos opc PopUpMenu
            this.pMenuColores.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseClicked

    private void mniVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVerdeActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.green);
    }//GEN-LAST:event_mniVerdeActionPerformed

    private void mniAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAzulActionPerformed
        // TODO add your handling code here:
        this.getContentPane().setBackground(Color.blue);
    }//GEN-LAST:event_mniAzulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejemplo13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejemplo13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejemplo13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejemplo13.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejemplo13().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem mniAzul;
    private javax.swing.JMenuItem mniRojo;
    private javax.swing.JMenuItem mniVerde;
    private javax.swing.JPopupMenu pMenuColores;
    // End of variables declaration//GEN-END:variables
}
