/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controladores.CuentasControl;
import controladores.MovimientoControl;
import controladores.UsuarioControl;
import entidades.Cuenta;
import entidades.Usuario;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;
import org.jvnet.substance.utils.SubstanceConstants;

/**
 *
 * @author spena
 */
public class Cajero extends javax.swing.JFrame {

    Usuario usuario = Login.usuarioValidado;
    List<Cuenta> lstCuentas;

    /**
     * Creates new form Cajero
     */
    public Cajero() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dlgCuentas.setLocationRelativeTo(null);
        this.dlgRetiro.setLocationRelativeTo(null);
        this.dlgAbono.setLocationRelativeTo(null);
        this.btnSalir.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnAbono.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnConsulta.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnPagoServicio.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnTransferencias.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnRetiro.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.btnRetiro.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.RIGHT);
        this.btnConsulta.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.RIGHT);
        this.btnSalir.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.RIGHT);
        this.btnAbono.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.LEFT);
        this.btnPagoServicio.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.LEFT);
        this.btnTransferencias.putClientProperty(SubstanceLookAndFeel.BUTTON_SIDE_PROPERTY, SubstanceConstants.Side.LEFT);
    }

    public void verCuentas() {
        DefaultListModel modelo = new DefaultListModel();
        lstCuentas = new ArrayList<>();
        lstCuentas = CuentasControl.listarCuentasUsuario(usuario);
        for (Cuenta cuentaActual : lstCuentas) {  //foreach          for(Clase objeto : lstClase)
            modelo.addElement(cuentaActual);
        }
        lstCuentasUsuario.setModel(modelo);
    }

    public void cargarComboCuentas() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        lstCuentas = new ArrayList<>();
        lstCuentas = CuentasControl.listarCuentasUsuario(usuario);
        for (Cuenta cuentaActual : lstCuentas) {
            modelo.addElement(cuentaActual);
        }
        cbxCuentas.setModel(modelo);
        cbxCuentasAbono.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlgCuentas = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCuentasUsuario = new javax.swing.JList<>();
        dlgRetiro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        cbxCuentas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spnMontoRetiro = new javax.swing.JSpinner();
        btnAceptarRetiro = new javax.swing.JButton();
        dlgAbono = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        spnAbono = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        cbxCuentasAbono = new javax.swing.JComboBox<>();
        btnAbonarCuenta = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTransferencias = new javax.swing.JButton();
        btnAbono = new javax.swing.JButton();
        btnPagoServicio = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        dlgCuentas.setTitle("Facilitador Salvador Peña");

        lstCuentasUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTADO DE CUENTAS Y SALDOS"));
        jScrollPane1.setViewportView(lstCuentasUsuario);

        javax.swing.GroupLayout dlgCuentasLayout = new javax.swing.GroupLayout(dlgCuentas.getContentPane());
        dlgCuentas.getContentPane().setLayout(dlgCuentasLayout);
        dlgCuentasLayout.setHorizontalGroup(
            dlgCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCuentasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        dlgCuentasLayout.setVerticalGroup(
            dlgCuentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgCuentasLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        dlgRetiro.setTitle("Facilitador Salvador Peña");

        jLabel1.setText("Seleccione la cuenta:");

        jLabel2.setText("RETIRO DE EFECTIVO");

        jLabel3.setText("Digite el monto a retirar: ");

        btnAceptarRetiro.setText("Aceptar");
        btnAceptarRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgRetiroLayout = new javax.swing.GroupLayout(dlgRetiro.getContentPane());
        dlgRetiro.getContentPane().setLayout(dlgRetiroLayout);
        dlgRetiroLayout.setHorizontalGroup(
            dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRetiroLayout.createSequentialGroup()
                .addGroup(dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAceptarRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dlgRetiroLayout.createSequentialGroup()
                            .addGap(194, 194, 194)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dlgRetiroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spnMontoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dlgRetiroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1)
                            .addGap(29, 29, 29)
                            .addComponent(cbxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        dlgRetiroLayout.setVerticalGroup(
            dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgRetiroLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(dlgRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnMontoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAceptarRetiro)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel4.setText("Cantidad a abonar");

        jLabel5.setText("Seleccione la cuenta:");

        btnAbonarCuenta.setText("GUARDAR ABONO A CUENTA");
        btnAbonarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlgAbonoLayout = new javax.swing.GroupLayout(dlgAbono.getContentPane());
        dlgAbono.getContentPane().setLayout(dlgAbonoLayout);
        dlgAbonoLayout.setHorizontalGroup(
            dlgAbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAbonoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlgAbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlgAbonoLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxCuentasAbono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dlgAbonoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(spnAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlgAbonoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAbonarCuenta)
                .addGap(144, 144, 144))
        );
        dlgAbonoLayout.setVerticalGroup(
            dlgAbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgAbonoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(dlgAbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCuentasAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(dlgAbonoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnAbono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnAbonarCuenta)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facilitador Salvador Peña");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cajero Automatico. Seleccione una opción:"));

        btnTransferencias.setText("<html>Transferencias a <br/>Cuentas Propias</html>");
        btnTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciasActionPerformed(evt);
            }
        });

        btnAbono.setText("Abono a cuenta");
        btnAbono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonoActionPerformed(evt);
            }
        });

        btnPagoServicio.setText("Pago de Servicios");

        btnRetiro.setText("Retiro de Efectivo");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consulta de Saldos");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPagoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferencias)
                    .addComponent(btnAbono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnRetiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPagoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAbono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        // TODO add your handling code here:
        this.dlgCuentas.pack();
        this.dlgCuentas.show();
        verCuentas();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
        this.dlgRetiro.pack();
        this.dlgRetiro.show();
        cargarComboCuentas();
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnAceptarRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarRetiroActionPerformed
        // TODO add your handling code here:
        BigDecimal montoRetirar = new BigDecimal(this.spnMontoRetiro.getValue().toString());
        Cuenta cuenta = (Cuenta) this.cbxCuentas.getSelectedItem();
        if (montoRetirar.compareTo(cuenta.getSaldo()) == 1) {
            JOptionPane.showMessageDialog(null, "El monto a retirar sobrepasa el saldo de la cuenta");
        } else {
            MovimientoControl.guardarRetiro(cuenta, montoRetirar);
            JOptionPane.showMessageDialog(null, "RETIRO REALIZADO");
        }
        cargarComboCuentas();
    }//GEN-LAST:event_btnAceptarRetiroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonoActionPerformed
        // TODO add your handling code here:
        this.dlgAbono.pack();
        this.dlgAbono.show();
        cargarComboCuentas();
    }//GEN-LAST:event_btnAbonoActionPerformed

    private void btnAbonarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarCuentaActionPerformed
        // TODO add your handling code here:
        BigDecimal montoAbonar = new BigDecimal(this.spnAbono.getValue().toString());
        Cuenta cuenta = (Cuenta) this.cbxCuentasAbono.getSelectedItem();
        MovimientoControl.guardarAbono(cuenta, montoAbonar);
        JOptionPane.showMessageDialog(null, "ABONO A CUENTA REALIZADO");
        cargarComboCuentas();

    }//GEN-LAST:event_btnAbonarCuentaActionPerformed

    private void btnTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTransferenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        JFrame.setDefaultLookAndFeelDecorated(true); //que nos permite dejar a Substance la decoracion ( por asi decirlo) 
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.RavenGraphiteGlassSkin");
        SubstanceLookAndFeel.setCurrentTheme("org.jvnet.substance.theme.SubstanceEbonyTheme");
        SubstanceLookAndFeel.setCurrentWatermark("org.jvnet.substance.watermark.SubstanceMarbleVeinWatermark");


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonarCuenta;
    private javax.swing.JButton btnAbono;
    private javax.swing.JButton btnAceptarRetiro;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnPagoServicio;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTransferencias;
    private javax.swing.JComboBox<String> cbxCuentas;
    private javax.swing.JComboBox<String> cbxCuentasAbono;
    private javax.swing.JDialog dlgAbono;
    private javax.swing.JDialog dlgCuentas;
    private javax.swing.JDialog dlgRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> lstCuentasUsuario;
    private javax.swing.JSpinner spnAbono;
    private javax.swing.JSpinner spnMontoRetiro;
    // End of variables declaration//GEN-END:variables
}
