
CREATE DATABASE EVALUACION_MOD3_JAVA
GO

USE EVALUACION_MOD3_JAVA

CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO int identity primary key not null,
	NOMBRE varchar(100)
)
GO

CREATE TABLE EMPLEADO(
	ID_EMPLEADO int primary key identity not null,
	NOMBRE varchar(150),
	DEPARTAMENTO int,
	SALARIO DECIMAL(12,2)
)
GO


ALTER TABLE EMPLEADO ADD FOREIGN KEY(DEPARTAMENTO)
REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)


INSERT INTO DEPARTAMENTO(NOMBRE) VALUES ('IT'), ('VENTAS')
SELECT * FROM DEPARTAMENTO 

INSERT INTO EMPLEADO (NOMBRE, DEPARTAMENTO, SALARIO) VALUES ('Alejandro Velasco', 1, '1000'), ( 'Diana Murcia', 2, '1000')


SELECT E.ID_EMPLEADO, E.NOMBRE, D.NOMBRE, E.SALARIO 
 FROM EMPLEADO E INNER JOIN DEPARTAMENTO D ON
 E.DEPARTAMENTO = D.ID_DEPARTAMENTO
 
 